--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VsrStudio/SimpleNPCWorldPlayerCount
build-by-default: true
branches:
- master
projects:
  SimpleNPCWorldPlayerCount:
    path: ""
...
